export const RepositoriesSymbols: Record<string, symbol> = {
	CalculatorRepository: Symbol.for('CalculatorRepository'),
	CalculatorRepositoryService: Symbol.for('CalculatorRepositoryService'),
	CountryRepository: Symbol.for('CountryRepository'),
	CalculatorCountryRepository: Symbol.for('CalculatorCountryRepository'),
	CalcCountryRepositoryService: Symbol.for('CalcCountryRepositoryService'),
	ProvinceRepository: Symbol.for('ProvinceRepository'),
	CalculatorProvinceRepository: Symbol.for('CalculatorProvinceRepository'),
	CalculatorProvinceRepositoryService: Symbol.for('CalculatorProvinceRepositoryService'),
	PlanRepository: Symbol.for('PlanRepository'),
	PlanPriceRepository: Symbol.for('PlanPriceRepository'),
	PlanRepositoryService: Symbol.for('PlanRepositoryService'),
	SubscriptionRepository: Symbol.for('SubscriptionRepository'),
	SubscriptionRepositoryService: Symbol.for('SubscriptionRepositoryService'),
	ClientRepository: Symbol.for('ClientRepository'),
	DataSource: Symbol.for('DataSource'),
	SubscriptionStatusRepository: Symbol.for('SubscriptionStatusRepository'),
	PaymentFrequencyRepository: Symbol.for('PaymentFrequencyRepository'),
	ExpertRepository: Symbol.for('ExpertRepository'),
	ExpertTypeRepository: Symbol.for('ExpertTypeRepository'),
	ExpertStatusRepository: Symbol.for('ExpertStatusRepository'),
	ExpertiseCountryRepository: Symbol.for('ExpertiseCountryRepository'),
	GetExpertListService: Symbol.for('GetExpertListService'),
	CreateExpertService: Symbol.for('CreateExpertService'),
};
